### ISSUE TITLE
Content package won't install

### ISSUE THREAD

**Issue by giveen** [xnih/satori#11]
```
Caused by: org.graylog2.contentpacks.exceptions.DivergingEntityConfigurationException: Different pipeline rule sources for pipeline rule with name "convert_timestamp_from_log"
        at org.graylog2.contentpacks.facades.PipelineRuleFacade.compareRuleSources(PipelineRuleFacade.java:151) ~[graylog.jar:?]
        at org.graylog2.contentpacks.facades.PipelineRuleFacade.findExisting(PipelineRuleFacade.java:140) ~[graylog.jar:?]
        at org.graylog2.contentpacks.facades.PipelineRuleFacade.findExisting(PipelineRuleFacade.java:126) ~[graylog.jar:?]
        at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:131) ~[graylog.jar:?]
```

As soon as I remove this section, it will install with no issues.

**Comment by xnih** [comment]
Upon more digging this was because there was already a pipeline named the same thing in their install.  Renamed all my pipleline rules to satori- and updated the json in the repository.
